In [5]:
import pandas as pd
import numpy as np

In [6]:
df= pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [24]:
pd.__version__

'3.0.6'

In [25]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [26]:
df['fuel_type'].nunique()

3

In [16]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [18]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [20]:
df['horsepower'].median()

np.float64(254.0)

In [50]:
horse_power_mode=df['horsepower'].mode()[0]
horse_power_mode

np.float64(252.0)

In [51]:
df['horsepower'].fillna(horse_power_mode).median()

np.float64(252.0)

In [64]:
asia=df[df['origin']=='Asia']

In [73]:
asia=asia[['vehicle_weight','model_year']].head(7)
asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [82]:
X=np.zeros((7,2))

In [83]:
X[:,0]=asia['vehicle_weight']
X[:,1]=asia['model_year']
X

array([[4240., 1996.],
       [4310., 1992.],
       [4230., 1997.],
       [4420., 1978.],
       [3950., 2007.],
       [4750., 2021.],
       [4450., 2019.]])

In [90]:
XT=X.T

In [91]:
XTX_inv=np.linalg.inv((XT).dot(X))
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [92]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [93]:
w=(XTX_inv.dot(XT)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [94]:
w.sum()

np.float64(0.36919696904925486)